### ISSUE TITLE
File not Found

### ISSUE THREAD

**Issue by Phedona** [dhinakg/vm-rpc#10]
PS C:\Users\user\vm-rpc> python main.py
Connected to RPC.
Please note that Discord has a 15 second ratelimit in sending Rich Presence updates.
Traceback (most recent call last):
  File "C:\Users\user\vm-rpc\main.py", line 143, in <module>
    vmware.updateOutput()
  File "C:\Users\user\vm-rpc\vmware.py", line 18, in updateOutput
    output = subprocess.run([str(self.vmrunpath), "list"], stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 546, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

no idea if I'm the problem, a small solution would be nice!

**Comment by dhinakg** [comment]
What VMware product and version are you using?
