### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by eveee00** [dhinakg/vm-rpc#15]
When trying to run i get this:
```
Connected to RPC.
Please note that Discord has a 15 second ratelimit in sending Rich Presence updates.
Traceback (most recent call last):
  File "X:\Desktop\vm-rpc-master\main.py", line 218, in <module>
    virtualbox.updateOutput()
  File "X:\Desktop\vm-rpc-master\virtualbox.py", line 25, in updateOutput
    output = subprocess.run([str(self.vmrunpath), "list", "runningvms"], stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```
`Das System kann die angegebene Datei nicht finden` means `The system couldn't fin the file specified`
Here's a screenshot:
![grafik](https://github.com/dhinakg/vm-rpc/assets/83956322/f7ded4d2-73fa-48ff-aecc-5259380ff1b6)

**Comment by Letalandroid** [comment]
If use VMWare with me, i'm comment this block code
```py
'''if "virtualbox" in hypervisors:
    virtualbox.updateOutput()
    if virtualbox.isRunning() == False:
        # No VMs running, clear rich presence and set time to update on next change
        clear()
    elif virtualbox.runCount() > 1:
        running = True
        # Too many VMs to fit in field
        STATUS = "Running VMs"
        # Get VM count so we can show how many are running
        vmcount = [virtualbox.runCount(), virtualbox.runCount()]
        HYPERVISOR = "VirtualBox"
    else:
        running = True
        # Init variable
        displayName = virtualbox.getRunningGuestName(0)
        STATUS = "Virtualizing " + displayName # Set status
        vmcount = None # Only 1 VM, so set vmcount to None
        HYPERVISOR = "VirtualBox"'''
```

# Example

https://github.com/user-attachments/assets/cf54fb7d-cc00-4a1a-aa95-24086826aef3
