### ISSUE TITLE
Doesnt run.

### ISSUE THREAD

**Issue by MarkCX1** [dhinakg/vm-rpc#16]
C:\Users\myuser\Desktop\Hyper-V\vm-rpc-master\vm-rpc-master>main.py
Connected to RPC.
Please note that Discord has a 15 second ratelimit in sending Rich Presence updates.
Traceback (most recent call last):
  File "C:\Users\myuser\Desktop\Hyper-V\vm-rpc-master\vm-rpc-master\main.py", line 175, in <module>
    vmware.updateOutput()
  File "C:\Users\myuser\Desktop\Hyper-V\vm-rpc-master\vm-rpc-master\vmware.py", line 18, in updateOutput
    output = subprocess.run([str(self.vmrunpath), "list"], stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Letalandroid** [comment]
If use VMWare with me, i'm comment this block code
```py
'''if "virtualbox" in hypervisors:
    virtualbox.updateOutput()
    if virtualbox.isRunning() == False:
        # No VMs running, clear rich presence and set time to update on next change
        clear()
    elif virtualbox.runCount() > 1:
        running = True
        # Too many VMs to fit in field
        STATUS = "Running VMs"
        # Get VM count so we can show how many are running
        vmcount = [virtualbox.runCount(), virtualbox.runCount()]
        HYPERVISOR = "VirtualBox"
    else:
        running = True
        # Init variable
        displayName = virtualbox.getRunningGuestName(0)
        STATUS = "Virtualizing " + displayName # Set status
        vmcount = None # Only 1 VM, so set vmcount to None
        HYPERVISOR = "VirtualBox"'''
```

# Example

https://github.com/user-attachments/assets/cf54fb7d-cc00-4a1a-aa95-24086826aef3
